# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guozhen Cheng
email: guozhencheng@hotmail.com
myName: 程国振

description: > # this means to ignore newlines until "baseurl:"
  Record my study notes for SDN, NFV, datacenter, et al.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chengguozhen.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  chengguozhen
permalink: /:year/:month/:day/:title/
excerpt_separator: "\n\n\n"

# Build settings
#markdown: kramdown

timezone: Asia/Beijing
highlighter: rouge
# highlighter: false
gems:
  - jekyll-sitemap
